version: '3'

services:
    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8080:80"
            # - "443:443"
        volumes:
            - ./configs/nginx:/etc/nginx/conf.d
            - ./src:/var/www/html
        depends_on:
            - app
        networks:
            - internal
    app:
        image: php:8.2-fpm
        # https://stackoverflow.com/a/43290357/7162445
        working_dir: "/var/www"
        volumes:
            - ./src:/var/www/html   
        networks:
            - internal

networks:
    internal:
        name: internal

